services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: hr-assistant-postgres
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5434:5432"
    volumes:
      - hr-assistant-pgdata:/var/lib/postgresql

volumes:
  hr-assistant-pgdata:
